import { ClinicalRule } from './types';

export const FacewashRules: Record<string, ClinicalRule> = {
  KERING_FALSE_BIASA: {
    dasarKlinis: "Pembersih wajah kulit kering biasa dengan kapasitas eksfoliasi optimal untuk mengangkat sebum dan tumpukan sel mati.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 6,
    harsh: { status: "DIIZINKAN", maxLoad: 4 },
    buffer: { status: "DIIZINKAN", minLoad: 0 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_FALSE_SEDANG: {
    dasarKlinis: "Pembersih wajah dengan surfaktan lembut dan eksfolian sedang untuk meredakan inflamasi jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 2 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_FALSE_PARAH: {
    dasarKlinis: "Pembersih kulit kering jerawat parah dilarang menggunakan eksfolian keras guna mencegah kerusakan skin barrier lebih lanjut.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_TRUE_BIASA: {
    dasarKlinis: "Pembersih lembut non-irritating untuk kulit kering sensitif dengan toleransi eksfolian sangat ringan guna mencegah penyumbatan pori.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 6,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_TRUE_SEDANG: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit kering sensitif jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_TRUE_PARAH: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit kering sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_BIASA: {
    dasarKlinis: "Pembersih wajah kulit berminyak biasa dengan kapasitas eksfoliasi optimal untuk mengangkat sebum dan tumpukan sel mati.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 4 },
    buffer: { status: "DIIZINKAN", minLoad: 0 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_SEDANG: {
    dasarKlinis: "Pembersih wajah dengan surfaktan lembut dan eksfolian sedang untuk meredakan inflamasi jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DIIZINKAN", maxLoad: 2 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_PARAH: {
    dasarKlinis: "Pembersih kulit berminyak jerawat parah dilarang menggunakan eksfolian keras guna mencegah kerusakan skin barrier lebih lanjut.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_BIASA: {
    dasarKlinis: "Pembersih lembut non-irritating untuk kulit berminyak sensitif dengan toleransi eksfolian sangat ringan guna mencegah penyumbatan pori.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_SEDANG: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit berminyak sensitif jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_PARAH: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit berminyak sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_BIASA: {
    dasarKlinis: "Pembersih wajah kulit kombinasi biasa dengan kapasitas eksfoliasi optimal untuk mengangkat sebum dan tumpukan sel mati.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 4 },
    buffer: { status: "DIIZINKAN", minLoad: 0 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_SEDANG: {
    dasarKlinis: "Pembersih wajah dengan surfaktan lembut dan eksfolian sedang untuk meredakan inflamasi jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DIIZINKAN", maxLoad: 2 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_PARAH: {
    dasarKlinis: "Pembersih kulit kombinasi jerawat parah dilarang menggunakan eksfolian keras guna mencegah kerusakan skin barrier lebih lanjut.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_BIASA: {
    dasarKlinis: "Pmarkers lembut non-irritating untuk kulit kombinasi sensitif dengan toleransi eksfolian sangat ringan guna mencegah penyumbatan pori.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_SEDANG: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit kombinasi sensitif jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_PARAH: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit kombinasi sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_BIASA: {
    dasarKlinis: "Pembersih wajah kulit normal biasa dengan kapasitas eksfoliasi optimal untuk mengangkat sebum dan tumpukan sel mati.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 5,
    harsh: { status: "DIIZINKAN", maxLoad: 4 },
    buffer: { status: "DIIZINKAN", minLoad: 0 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_SEDANG: {
    dasarKlinis: "Pembersih wajah dengan surfaktan lembut dan eksfolian sedang untuk meredakan inflamasi jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 2 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_PARAH: {
    dasarKlinis: "Pembersih kulit normal jerawat parah dilarang menggunakan eksfolian keras guna mencegah kerusakan skin barrier lebih lanjut.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_BIASA: {
    dasarKlinis: "Pembersih lembut non-irritating untuk kulit normal sensitif dengan toleransi eksfolian sangat ringan guna mencegah penyumbatan pori.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 5,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_SEDANG: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit normal sensitif jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_PARAH: {
    dasarKlinis: "Pembersih bebas surfaktan keras wajib ditenangkan tanpa eksfoliasi aktif untuk kulit normal sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  }
};
