import { ClinicalRule } from './types';

export const FacewashRules: Record<string, ClinicalRule> = {
  "KOMBINASI_FALSE_BIASA": {
    dasarKlinis: "Kulit kombinasi dengan komedo ringan memerlukan surfaktan berdaya bersih optimal untuk mengangkat sebum teroksidasi tanpa mendisrupsi lapisan lipid fundamental. Penggunaan eksfolian ringan tingkat harsh rendah terbukti memecah mikrokomedo secara efektif tanpa efek samping berlebih.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_FALSE_SEDANG": {
    dasarKlinis: "Kehadiran papula dan pustula inflamasi menuntut penurunan variabilitas surfaktan untuk mencegah iritasi mekanis pada lesi meradang. Sistem buffer stabil diperlukan guna mendukung lingkungan pH asam yang menghambat proliferasi bakteri patogen.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_FALSE_PARAH": {
    dasarKlinis: "Lesi nodulokistik kronis dengan disfungsi barrier ekstrim mengharuskan pembersihan bebas lipid komedogenik dengan satu agen surfaktan ultra-mild absolut minimum. Eliminasi total bahan harsh wajib dieksekusi untuk mencegah eksaserbasi kista akibat abrasi kimiawi pada inflamasi dalam.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DIIZINKAN", minCount: 1, maxCount: 1 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_BIASA": {
    dasarKlinis: "Reaktivitas neurogenik pada kulit sensitif mempersempit jendela toleransi terhadap surfaktan, menuntut substitusi pembersih abrasif dengan matriks kaya humektan pengikat air. Potensi penyumbatan silang dikendalikan melalui limitasi ketat pada agen komedogenik tunggal dan deposisi bahan pemicu acne cosmetica sekunder.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_SEDANG": {
    dasarKlinis: "Formulasi pembersih harus bertindak murni mengangkat kotoran hidrofilik tanpa memicu kaskade eritema pada pustula sensitif yang distabilkan oleh sistem buffer tingkat kuat. Beban akumulatif komedogenik dikunci mendekati titik nol absolut untuk menghambat folikulitis meluas.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_PARAH": {
    dasarKlinis: "Tingkat kerusakan arsitektur kistik dan kerentanan alergenik menetapkan kebutuhan formulasi pencuci dengan kualifikasi komedogenik skala nol mutlak. Intervensi penambahan humektan berat diimplementasikan murni untuk meredam syok osmotik yang biasa merusak integritas sawar kulit saat kontak dengan air.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DIIZINKAN", minCount: 1, maxCount: 1 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_BIASA": {
    dasarKlinis: "Surfaktan ringan hingga sedang esensial untuk menurunkan tegangan permukaan dan melarutkan sebum tanpa menyebabkan denaturasi masif pada keratin korneosit. Agen keratolitik tingkat menengah direkomendasikan untuk mengekstraksi penyumbatan mikrokomedo secara efektif.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DIIZINKAN", maxLoad: 3 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 4 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_SEDANG": {
    dasarKlinis: "Peningkatan inflamasi folikel membatasi kemampuan epidermis mentoleransi misel surfaktan yang berlebihan. Penurunan kuantitas eksfolian mencegah kaskade sitokin pro-inflamasi sambil tetap mempertahankan fungsi eliminasi sel kulit mati.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DIIZINKAN", maxLoad: 3 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_PARAH": {
    dasarKlinis: "Fisiologi lesi kistik menandakan kerusakan arsitektur dermis yang parah, sehingga disolusi lemak yang agresif akan sangat memperburuk defek. Kondisi ini mewajibkan pembersihan menggunakan pelarut murni dengan sistem penyangga pH yang kuat untuk melindungi mantel asam tanpa mengiritasi.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_BIASA": {
    dasarKlinis: "Ekstensi ujung saraf sensorik yang reaktif pada kulit sensitif meningkatkan permeabilitas penetrasi senyawa kimia secara instan. Oleh karena itu, penggunaan bahan asam eksfoliatif harus dibatasi pada level rendah dan diimbangi buffer kuat agar pH tetap berada di atas 4.5.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_SEDANG": {
    dasarKlinis: "Hiper-reaktivitas patologis yang bersilangan dengan lesi inflamasi membutuhkan eliminasi mutlak semua entitas iritan dari fase pencucian wajah. Formulasi wajib dialihkan pada agen pembersih non-ionik yang didukung asupan ceramide untuk merekatkan kembali mikro-robekan korneosit.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_PARAH": {
    dasarKlinis: "Kulit mempresentasikan kegagalan homeostasis masif sehingga mewajibkan pembersihan bebas lipid untuk memfasilitasi penguapan kotoran tanpa menarik sebum esensial dari matriks. Humektan hidrofilik diwajibkan untuk mendinginkan saraf sensorik dan mempertahankan skor komedogenik pada titik absolut nol.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 1 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_FALSE_BIASA": {
    dasarKlinis: "Waktu kontak bilas yang singkat mentolerir agen pembersih efisien dan batas komedogenik menengah tanpa residu kumulatif bermakna. Kapasitas penyangga (buffer) diperlukan untuk memastikan transisi pemulihan pH isoelektrik kulit pasca-pembersihan.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 4,
    harsh: { status: "DIIZINKAN", maxLoad: 3 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 4 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 2 },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "NORMAL_FALSE_SEDANG": {
    dasarKlinis: "Peningkatan keparahan jerawat menuntut perbaikan fasa hidrasi untuk mencegah respons produksi sebum kompensatori akibat aktivitas pembersihan. Potensi iritan keras mulai ditekan dan parameter penahan air wajib dinaikkan.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 2 },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "NORMAL_FALSE_PARAH": {
    dasarKlinis: "Lesi inflamasi kistik sangat rentan terhadap surfaktan mendenaturasi yang dapat memicu perkembangbiakan bakteri anaerobik. Sifat harsh dilarang sepenuhnya dan digantikan oleh buffer berkapasitas tinggi untuk mengatur lingkungan kulit yang asam.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_BIASA": {
    dasarKlinis: "Defisit protein pada kulit sensitif meningkatkan kerentanan pelucutan lipid struktural oleh surfaktan pencuci. Fasa emolien diwajibkan demi mengisi celah hidrasi epidermis seketika setelah paparan air usai.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "NORMAL_TRUE_SEDANG": {
    dasarKlinis: "Disfungsi pelindung seluler yang bersilangan dengan eritema peradangan menyaratkan metode pencucian yang teramat lembut. Skala risiko sumbatan diturunkan dan tingkat kekuatan buffer ditingkatkan secara defensif.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_PARAH": {
    dasarKlinis: "Kondisi inflamasi kistik pada kulit sensitif melarang eksistensi seluruh matriks komedogenik multi yang berpotensi memerangkap sebum persisten. Rekayasa berpusat penuh pada kombinasi humektan air dan lipid reparatif di bawah dukungan lingkungan pH yang diatur secara ketat.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_BIASA": {
    dasarKlinis: "Pembersihan pada kulit kering dengan jerawat ringan memerlukan surfaktan berukuran misel besar untuk melarutkan sebum tanpa mengekstraksi lipid esensial stratum corneum. Penambahan humektan hidrofilik diwajibkan untuk mencegah efek ketat pasca-pencucian yang dapat memicu kompensasi sebum reaktif.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 1 },
    surfactant: { status: "WAJIB", minCount: 2, maxCount: 3 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_SEDANG": {
    dasarKlinis: "Peningkatan aktivitas papulopustular menuntut penghentian agen harsh sepenuhnya untuk mencegah perluasan inflamasi, sedangkan surfaktan polimerik digunakan secara konservatif. Integrasi pelembap air dalam konsentrasi tinggi diperlukan untuk menopang elastisitas jaringan yang sedang meradang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_PARAH": {
    dasarKlinis: "Fase kistik dan nodular akut memanifestasikan kerusakan epitel parah yang sangat rentan terhadap friksi dan bahan oklusif. Pembersih harus memiliki profil komedogenik mendekati nol dan sistem penyangga pH menengah hingga kuat untuk melindungi mantel asam kulit dari alkalinisasi.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_BIASA": {
    dasarKlinis: "Interseksi antara kondisi hipersensitif dan kekeringan memandatkan stabilitas termodinamika absolut melalui agen buffer, sekaligus menghindari agen sitotoksik dan eksfolian iritatif. Lipid sedang diperkenalkan ulang sebagai pelumas pelindung untuk meredam reaktivitas vaskular (kemerahan) saat dibilas.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_SEDANG": {
    dasarKlinis: "Stres peradangan akibat jerawat dikombinasikan dengan kerentanan ujung saraf memerlukan sistem pembersih dengan molekul ultra-ringan dengan kapasitas penyangga pH tinggi. Sinergi bahan komedogenik level rendah dibatasi sangat ketat untuk menghindari penyumbatan sekunder.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 2 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_PARAH": {
    dasarKlinis: "Kondisi dermatologis paling krisis ini mengharamkan toleransi terhadap potensi oklusi atau agen iritatif sekecil apa pun; matriks formulasi pembersih harus sepenuhnya hidrofilik murni. Kapasitas buffer kuat absolut diwajibkan untuk menstabilkan bioma tanpa menggunakan agen penekan lipid tambahan.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "WAJIB", minCount: 1, maxCount: 1 },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
};
