import { ClinicalRule } from './types';

export const MoisturizerRules: Record<string, ClinicalRule> = {
  KERING_FALSE_BIASA: {
    dasarKlinis: "Pelembap oklusif kaya lipid penyeimbang barrier kulit untuk tipe kulit kering biasa guna menahan penguapan air.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 6,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" }
  },
  KERING_FALSE_SEDANG: {
    dasarKlinis: "Pelembap emolien hidrasi sedang dengan perlindungan komedogenik ketat untuk kulit kering jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" }
  },
  KERING_FALSE_PARAH: {
    dasarKlinis: "Pelembap kaya emolien non-komedogenik bebas minyak berat untuk memitigasi lesi meradang parah kulit kering.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_TRUE_BIASA: {
    dasarKlinis: "Pelembap oklusif emolien minimal bebas wewangian dan alkohol pengering untuk menghidrasi kulit kering sensitif.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 6,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" }
  },
  KERING_TRUE_SEDANG: {
    dasarKlinis: "Pelembap sensitif non-komedogenik emolien sedang dengan penenang aktif untuk kulit kering sensitif jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" }
  },
  KERING_TRUE_PARAH: {
    dasarKlinis: "Pelembap penenang murni bebas minyak dan bahan oklusif berat untuk memitigasi barrier rusak kulit kering sensitif parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_BIASA: {
    dasarKlinis: "Pelembap gel hidrasi ringan bebas minyak berat untuk memitigasi kelebihan sebum kulit berminyak biasa.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_SEDANG: {
    dasarKlinis: "Pelembap gel hidrasi ringan non-komedogenik dengan batas eksfolian nihil untuk kulit berminyak jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_PARAH: {
    dasarKlinis: "Pelembap gel ultra ringan bebas minyak mutlak untuk memitigasi sebum berlebih dan jerawat parah kulit berminyak.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_BIASA: {
    dasarKlinis: "Pelembap gel sensitif bebas oklusif berat untuk menghidrasi kulit berminyak sensitif tanpa memicu sebum berlebih.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_SEDANG: {
    dasarKlinis: "Pelembap gel hidrasi ringan bebas pewangi dengan penenang aktif untuk kulit berminyak sensitif jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_PARAH: {
    dasarKlinis: "Pelembap gel ultra ringan dengan penenang murni bebas minyak mutlak untuk kulit berminyak sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_BIASA: {
    dasarKlinis: "Pelembap hibrida gel-krim dengan hidrasi seimbang tanpa oklusif berlebih untuk kulit kombinasi biasa.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_SEDANG: {
    dasarKlinis: "Pelembap krim-gel ringan non-komedogenik bebas emolien berat untuk kulit kombinasi jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_PARAH: {
    dasarKlinis: "Pelembap gel hidrasi bebas minyak oklusif berat untuk memitigasi sebum zona-T dan jerawat parah kulit kombinasi.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_BIASA: {
    dasarKlinis: "Pelembap krim-gel ringan sensitif bebas alkohol pengering untuk menghidrasi kulit kombinasi sensitif.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_SEDANG: {
    dasarKlinis: "Pelembap gel sensitif dengan hidrasi bebas minyak berat dan agen penenang untuk kulit kombinasi sensitif jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_PARAH: {
    dasarKlinis: "Pelembap gel ultra ringan bebas minyak dengan penenang kuat untuk kulit kombinasi sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_BIASA: {
    dasarKlinis: "Pelembap krim sedang hidrasi seimbang untuk mempertahankan barrier alami kulit normal biasa.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 5,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" }
  },
  NORMAL_FALSE_SEDANG: {
    dasarKlinis: "Pelembap gel-krim ringan bebas emolien berat untuk memitigasi lesi meradang kulit normal jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_PARAH: {
    dasarKlinis: "Pelembap gel hidrasi bebas minyak berat untuk memitigasi sebum zona-T dan jerawat parah kulit normal.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_BIASA: {
    dasarKlinis: "Pelembap sensitif sedang bebas alkohol pengering untuk menghidrasi kulit normal sensitif.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 5,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" }
  },
  NORMAL_TRUE_SEDANG: {
    dasarKlinis: "Pelembap gel sensitif hidrasi bebas minyak berat dengan penenang aktif untuk kulit normal sensitif jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_PARAH: {
    dasarKlinis: "Pelembap gel ultra ringan bebas minyak dengan penenang kuat untuk kulit normal sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  }
};
