import { ClinicalRule } from './types';

export const MoisturizerRules: Record<string, ClinicalRule> = {
  "KOMBINASI_FALSE_BIASA": {
    dasarKlinis: "Kulit kombinasi dengan mikrokomedo merespons optimal terhadap matriks pelembap yang menyinkronkan hidrasi air tingkat tinggi dengan persentase lipid ringan ekuimolar. Pemblokiran permanen spektrum pelembap minyak tebal diterapkan untuk menghindari oklusi termal masif pada kelenjar T-zone.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 1 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 3 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_FALSE_SEDANG": {
    dasarKlinis: "Degenerasi dinding stratum corneum akibat papula inflamasi mempercepat kehilangan air transepidermal, mengamanatkan reorientasi emulsi pada humektan higroskopik ekstensif bersama lipid ceramide spesifik. Formulasi wajib memangkas eksipien penyumbat komedogenik multipel yang sering memicu hiperkeratinisasi diam-diam di dinding folikel.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_FALSE_PARAH": {
    dasarKlinis: "Sindrom jerawat nodulokistik membutuhkan perbaikan stratum corneum melalui emulsi ceramide-air yang presisi tanpa menyertakan satupun spektrum komedogenik organik. Ketiadaan oklusif berat dipadukan dengan larutan penyangga (buffer) tingkat kuat guna memitigasi dan mengkoreksi asidosis intraseluler akibat luka purulen.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 2, maxCount: 4 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_BIASA": {
    dasarKlinis: "Kerentanan imunologis pada latar belakang kulit sensitif mengakibatkan intoleransi fluktuasi pH, mewajibkan inkorporasi senyawa buffer stabil guna menangkal episode eritema sensasi menyengat. Proyeksi resusitasi dialihkan murni pada humektan hidrofilik untuk menghindari oklusi molekuler yang memblokir proses respirasi kulit.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_SEDANG": {
    dasarKlinis: "Fase papulopustular kronis pada zona sensitif fokal menuntut hidrasi bervolume ekstensif dan penyegelan biomimetik yang dikhususkan pada kelompok sphingolipid struktural non-reaktif. Penghapusan komponen komedogenik hingga skala nol diwajibkan untuk mengompensasi hilangnya kemampuan alami unit folikel dalam meluruhkan sel nekrotik.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 2, maxCount: 3 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_PARAH": {
    dasarKlinis: "Intervensi terhadap serangan kistik pada pasien sensitif mutlak memandatkan deposisi matriks hidrogel penyembuh super-steril yang sama sekali menolak penumpukan oklusif viskos apapun. Regulasi nol-komedogenik absolut memegang mandat vital guna menghalangi pembentukan jerawat induksi dan mengarahkan air termodifikasi ion langsung ke situs radang.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 2, maxCount: 3 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_BIASA": {
    dasarKlinis: "Strategi rehidrasi mengutamakan sistem emulsi berviskositas rendah yang menyuplai air secara konstan tanpa mendistorsi dinamika sekresi sebum alami. Konstituen lipid disuplai dalam skala terbatas semata-mata untuk menjaga keutuhan struktur antarseluler.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 1,
    harsh: { status: "DIIZINKAN", maxLoad: 1 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_SEDANG": {
    dasarKlinis: "Risiko komedo tertutup menjadi erupsi persisten dimitigasi melalui pembatasan matematis terhadap interaksi aditif pada material komedogenik berskala rendah. Bahan perusak sawar dilarang sepenuhnya untuk mencegah efek pencucian berlebih dari terapi obat utama.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_PARAH": {
    dasarKlinis: "Segala bentuk oklusi pori memberikan kondisi anisotropik anaerobik yang secara langsung mengeksploitasi sekresi bakteri penyebab nodul kistik. Oleh karena itu, arsitektur pelembap disandarkan murni pada molekul pembawa air yang bebas dari partikulat minyak.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 1 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_BIASA": {
    dasarKlinis: "Defisit biogenesis protein pada sindrom kulit sensitif mengharuskan induksi lipid terstruktur seperti ceramide untuk menambal laju penguapan air transepidermal. Pelembap lipid diubah batasannya menjadi wajib guna merekonstruksi pertahanan seluler yang rentan.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_SEDANG": {
    dasarKlinis: "Berfungsi sebagai penyokong matriks yang menekan produksi sitokin inflamasi tanpa mengganggu keseimbangan mikrobioma alami kulit. Komponen penyebab iritasi dilarang secara absolut guna mencegah pelebaran luka mikroskopik pada dinding folikel.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_PARAH": {
    dasarKlinis: "Formulasi menghadapi denaturasi imun parah, sehingga dituntut mempertahankan parameter komedogenisitas dan oklusi pada titik terendah absolut. Eksekusi sistem bertumpu pada pelapisan humektan pendingin untuk menstabilkan suhu jaringan kulit yang meradang.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_FALSE_BIASA": {
    dasarKlinis: "Sebagai sediaan formulasi menetap, batas komedogenik ditarik ke skala aman guna menghindari proliferasi bakteri akibat inkubasi harian. Pelembap tipe oklusif diizinkan secara terbatas guna menahan penguapan air tanpa menyumbat pori.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 2 }
  },
  "NORMAL_FALSE_SEDANG": {
    dasarKlinis: "Ancaman oklusi pada jerawat moderat mengarahkan formulasi menuju spektrum gel-cream ringan yang bertindak sebagai penarik cairan. Matriks hidrofilik dibebankan tugas rehidrasi mayor untuk mensubstitusi pengurangan komponen minyak tebal.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "NORMAL_FALSE_PARAH": {
    dasarKlinis: "Kerusakan duktus sebasea pada inflamasi kistik parah menggugurkan kelayakan pelembap oklusif dan risiko interaksi komedogenik multi. Pertahanan sawar dialihkan murni pada ceramide lipid dan humektan air yang berskor keamanan sangat tinggi.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_BIASA": {
    dasarKlinis: "Kegagalan pelindung pada kulit sensitif direstorasi melalui fasa emolien kaya asam lemak yang sama sekali tidak mengiritasi. Interaksi ini dipertahankan oleh buffer moderat untuk menunjang metabolisme pembentukan lipid endogen.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "NORMAL_TRUE_SEDANG": {
    dasarKlinis: "Permukaan kulit reaktif menolak keberadaan molekul oklusif secara penuh guna menjaga kelancaran sirkulasi udara trans-epidermal. Peran bantalan kulit murni disuplai oleh porsi tinggi dari pelembap hidrasi air dan lipid pelindung.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_PARAH": {
    dasarKlinis: "Kelemahan imunoterapi kulit memutlakkan syarat skor komedogenik 0 guna membatasi inisiasi sel radang baru. Buffer berkonsentrasi kuat diinsersi untuk menghalau patogen secara pasif karena semua agen harsh harus ditiadakan.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_BIASA": {
    dasarKlinis: "Pengembalian matriks interseluler yang defisit memerlukan kombinasi seimbang antara pelembap air dan lipid guna meningkatkan elastisitas lapisan tanduk tanpa hiper-oklusi. Sedikit agen minyak tebal masih ditoleransi untuk menekan TEWL di area kulit yang sangat kering asalkan parameter komedogenik terkontrol.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 1 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "KERING_FALSE_SEDANG": {
    dasarKlinis: "Meningkatnya populasi bakteri jerawat akibat inflamasi moderat mengharuskan pelarangan total terhadap pelembap minyak hidrokarbon oklusif yang dapat menjebak panas dan sekresi sebasea di dalam pori. Restorasi hidrasi sepenuhnya diserahkan kepada humektan murni dan lipid non-comedogenic yang meredakan inflamasi.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_PARAH": {
    dasarKlinis: "Formulasi bergeser menjadi matriks gel-hidro yang sarat akan humektan, dengan lipid esensial diformulasikan dalam konsentrasi mikroskopik hanya untuk sinyal seluler perbaikan penghalang. Segala bentuk emulsi berat atau sinergi bahan berskala komedogenik diredam mendekati nol.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_BIASA": {
    dasarKlinis: "Restorasi sawar terkompromi pada kulit reaktif alergi sangat bergantung pada pemulihan rasio lipid fisiologis biomimetik, sehingga alokasi agen penambah lipid ditingkatkan. Kapasitas buffer sediaan ditinggalkan pada level sedang untuk membentengi respons pH kulit yang rapuh.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 2, maxCount: 3 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_SEDANG": {
    dasarKlinis: "Reseptor neuro-inflamasi merespons agregasi patogen jerawat dengan pelepasan histamin sehingga pelembap harus memberikan efek penyejuk langsung yang dipasok oleh volume cairan humektan dalam jumlah masif. Penguatan sistem penyangga level tinggi diberlakukan untuk meminimalkan fluktuasi enzimatik.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_PARAH": {
    dasarKlinis: "Integritas struktural kulit yang hancur menuntut penyediaan hidrasi intraseluler eksklusif bebas minyak dan murni non-comedogenic untuk mencegah reaksi antigenik. Penyangga asam tingkat terkuat digunakan demi merestorasi lapisan pelindung kulit secara artifisial.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 4, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
};
