import { ClinicalRule } from './types';

export const SunscreenRules: Record<string, ClinicalRule> = {
  "KOMBINASI_FALSE_BIASA": {
    dasarKlinis: "Konfigurasi perlindungan ultraviolet terhadap ekosistem kulit berkomedo memprioritaskan penyebaran filter organik yang dilarutkan ke dalam fase hidrator oil-in-water tingkat tinggi. Limitasi moderat eksipien berpotensi menyumbat dirancang spesifik untuk mencegah terjadinya perangkap suhu berlebih di dasar pori.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 1, maxCount: 4 },
    moistLight: { status: "DIIZINKAN", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_FALSE_SEDANG": {
    dasarKlinis: "Kemunculan papulopustular membatasi kuantitas molekul filter sintetis guna menahan insiden retensi paparan sinar termal yang memperburuk eritema kulit penderita. Pelembap difokuskan pada spektrum air ringan tanpa tambahan bahan komedogenik agar laju penyerapan pelindung UV tidak membebani kapiler sebasea.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 1, maxCount: 3 },
    moistLight: { status: "DIIZINKAN", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_FALSE_PARAH": {
    dasarKlinis: "Tabir surya kistik diwajibkan menyingkirkan filter berbasis kimia penetratif dan menggantinya dengan tameng mineral inorganik (zinc/titanium) tersuspensi pada humektan hidrogel pekat. Pemblokiran absolut untuk pelembap lipid dieksekusi guna menurunkan angka retensi energi foton yang merusak sawar terbuka.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_BIASA": {
    dasarKlinis: "Sensitivitas dermal secara tegas memerintahkan penghindaran filter ultraviolet kompleks pemicu dermatitis iritan, serta memaksa stabilisasi menggunakan penyangga (buffer) kapasitas kuat. Intervensi pelindungan diarahkan mengandalkan air berlimpah murni yang mengisolasi iritasi paparan matahari dari area T-zone sensitif.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_SEDANG": {
    dasarKlinis: "Reaktivitas terhadap lesi memandatkan satu hingga dua agen inorganik perlindungan seragam dalam dispersi yang 100% bebas dari segala eksipien penyumbat (nol komedogenik). Peniadaan pelembap lipid secara definitif diterapkan agar tidak mencetus lokalisasi panas yang kerap kali melebarkan dimensi papula peradangan subkutan.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistLight: { status: "DIIZINKAN", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KOMBINASI_TRUE_PARAH": {
    dasarKlinis: "Ekstremitas kistik inflamatori menghadapi energi matahari membutuhkan proteksi filter tunggal dengan gelombang inorganik statis dalam larutan air yang dikontrol matriks buffer sangat reaktif. Regulasi pelarangan absolut lipid emolien adalah jaminan klinis agar proses evaporasi sel pada lesi berongga tidak mengalami disrupsi oklusi termal.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "DIIZINKAN", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "DIIZINKAN", minCount: 1, maxCount: 1 },
    moistLight: { status: "DIIZINKAN", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_BIASA": {
    dasarKlinis: "Fotoproteksi memadai tercapai melalui kombinasi sinergis agen penapis spektrum luas tanpa memaksa penambahan emolien pekat yang berdampak oklusif kuat. Formulasi distabilkan dengan meniadakan bahan dasar lipofilik komedogenik berat penyebab jerawat kosmetika.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 4 },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_SEDANG": {
    dasarKlinis: "Absorpsi konversi panas dari tabir surya kimia menginduksi vasodilatasi yang kerap memperparah hiperpigmentasi pada fase penyembuhan kista jerawat. Regulasi jumlah molekul UV sintetik ditekan lebih rendah dan diganti dengan dukungan hidrator ringan pembawa efek sejuk.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 3 },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_FALSE_PARAH": {
    dasarKlinis: "Residu eksipien tabir surya berisiko langsung mengeksaserbasi proliferasi patogen folikular pada pori yang sedang terluka parah. Oleh karena itu, beban oklusif hidrokarbon dikunci di skala nol mutlak dan disisakan dispersi UV partikulat mineral yang lebih pasif.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 1 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_BIASA": {
    dasarKlinis: "Hipersensitivitas fototoksik menuntut restriksi ketat terhadap molekul tabir surya aromatik ganda untuk menghindari iritasi turunan. Matriks formulasi diarahkan pada perlindungan mineral ringan minimalis yang dipasangkan dengan agen penyeimbang sawar kulit.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_SEDANG": {
    dasarKlinis: "Kerentanan progresif akibat radiasi UV dan lesi jerawat menuntut profil pelindung klinis yang hampir inert dari sisi reaksi kimia. Asimilasi suhu radiasi ditangani sepenuhnya oleh pelarut hidrator sedangkan filter UV ditugaskan hanya pada molekul tunggal atau ganda berisiko rendah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "BERMINYAK_TRUE_PARAH": {
    dasarKlinis: "Keadaan bio-kritis dengan eritema vaskular mendestruksi toleransi epidermis terhadap hampir semua penapis sintetik. Resep difokuskan murni pada larutan berair ultra-ringan dengan satu filter mineral skala besar untuk menghindari penyumbatan intraseluler sama sekali.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 1 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 1 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_FALSE_BIASA": {
    dasarKlinis: "Residu radiasi dan filter UV sering memicu pengeringan sekunder, sehingga sediaan wajib ditopang oleh cairan hidrasi preventif. Filter UV majemuk ditoleransi pada kulit jerawat ringan asalkan matriks emulsinya moderat.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 5 },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 2 },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: 1 }
  },
  "NORMAL_FALSE_SEDANG": {
    dasarKlinis: "Risiko penumpukan fotoprotektor dan produk peroksidasi mengharuskan pemangkasan elemen minyak oklusif. Kuantitas filter dioptimalkan untuk melindungi kulit tanpa menaikkan beban termodinamika secara berlebih.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 4 },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_FALSE_PARAH": {
    dasarKlinis: "Filter ultraviolet harus ditempatkan dalam cairan ekstrim ringan yang tidak menyegel respirasi di atas nodul kistik yang aktif. Lapisan humektan dipertebal untuk menstabilkan suhu mikrokosmik dan mencegah fluktuasi air antar-sel.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 4 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_BIASA": {
    dasarKlinis: "Potensi sensitisasi alergi akibat tabir surya mewajibkan ketersediaan fasa lipid untuk melindungi sawar kulit pasien. Kapasitas buffer menghambat degradasi UV filter reaktif saat terpapar sinar.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 4 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_SEDANG": {
    dasarKlinis: "Reaksi neurogenik fotokontak diredam melalui kuota filter optis yang sangat selektif dan eliminasi seluruh zat oklusif. Tingkat hidrasi tinggi menjadi penengah termal utama di antara molekul fotoprotektor dan membran sel yang tipis.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "NORMAL_TRUE_PARAH": {
    dasarKlinis: "Kondisi fotodermatologi kritis menyaratkan tolerabilitas absolut dengan fiksasi filter pada matriks berkapasitas komedogenik nol. Mekanisme penyangga asam-basa mencegah kelumpuhan matriks tabir surya akibat reaksi radikal peradangan kistik.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 3 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_BIASA": {
    dasarKlinis: "Proteksi UV mutlak diperlukan guna menghentikan stres oksidatif lipid sebum dan formasi hiperpigmentasi melanin dengan formulasi berbasis krim ringan yang difasilitasi oleh sejumlah emolien untuk mengompensasi kekeringan. Sinergi bahan pembawa diperbolehkan dengan pengawasan komedogenik moderat.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 4 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_SEDANG": {
    dasarKlinis: "Partikulat UV filter dapat menimbulkan efek tumpang tindih dalam folikel sehingga formulasi harus dimodifikasi dari sediaan krim menjadi emulsi cair atau gel hidro-dinamis. Penggunaan lipid dibatasi sangat ketat untuk mencegah penumpukan residu pada kelenjar minyak yang sedang meradang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: 3 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_FALSE_PARAH": {
    dasarKlinis: "Kehadiran papul besar dan pustula menyarankan perlunya meminimalkan total beban bahan filter kimia menjadi matriks yang sangat spesifik untuk mencegah terperangkapnya zat pelindung di pori dalam. Cairan pelarut utama harus humektan penarik air bervolume maksimal.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_BIASA": {
    dasarKlinis: "Risiko fotodermatitis dan alergi dari senyawa organik memaksa pergeseran teknologi perisai surya menjadi murni mineral anorganik yang memantulkan radiasi tanpa masuk ke sirkulasi kapiler. Tingkat pH sediaan dikalibrasi ketat menggunakan senyawa buffer penenang yang stabil.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistLight: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_SEDANG": {
    dasarKlinis: "Stres ganda dari kerusakan sawar UV dan invasi jerawat merekomendasikan formulasi fotoprotektif berikatan hidrogen dengan oklusi pori yang nyaris dieliminasi seluruhnya. Seramida dalam batas wajar disisipkan demi mengurangi penguapan air akibat iklim mikro paparan matahari.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 1,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: 1 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
  "KERING_TRUE_PARAH": {
    dasarKlinis: "Skala cedera sel tertinggi ini mengharuskan perisai ultraviolet tidak menyumbang inflamasi atau iritasi seluler sedikit pun sehingga bergantung mutlak pada filter mineral bertekstur cair dan serum pelembap hiper-terfiltrasi. Validitas matriks harus mempertahankan status dilarang mutlak pada seluruh variabel penyebab jerawat.",
    maxSingleComedo: 0,
    maxMultiComedoLoad: 0,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 6 },
    surfactant: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 1, maxCount: 2 },
    moistLight: { status: "WAJIB", minCount: 3, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: "UNLIMITED" }
  },
};
