import { ClinicalRule } from './types';

export const SunscreenRules: Record<string, ClinicalRule> = {
  KERING_FALSE_BIASA: {
    dasarKlinis: "Tabir surya hibrida pelembap emolien hidrasi kaya lipid pelindung UV broad-spectrum kulit kering biasa.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 6,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" }
  },
  KERING_FALSE_SEDANG: {
    dasarKlinis: "Tabir surya mineral fisik dengan emolien minimal non-komedogenik ketat untuk kulit kering jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" }
  },
  KERING_FALSE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik murni bebas minyak oklusif berat untuk memitigasi lesi meradang parah kulit kering.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KERING_TRUE_BIASA: {
    dasarKlinis: "Tabir surya hipoalergenik non-iritan dengan emolien sedang pelindung UV untuk kulit kering sensitif.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 6,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" }
  },
  KERING_TRUE_SEDANG: {
    dasarKlinis: "Tabir surya mineral fisik bebas kimia sintetis pengiritasi kulit kering sensitif jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" }
  },
  KERING_TRUE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik murni bebas minyak dan oklusif berat dengan penenang aktif kulit kering sensitif parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_BIASA: {
    dasarKlinis: "Tabir surya gel cair atau fluid ringan non-komedogenik bebas minyak oklusif untuk kulit berminyak biasa.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_SEDANG: {
    dasarKlinis: "Tabir surya fluid sebum-control ultra ringan bebas emolien berat untuk kulit berminyak jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_FALSE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik ultra ringan bebas lipid oklusif untuk memitigasi jerawat parah kulit berminyak.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_BIASA: {
    dasarKlinis: "Tabir surya sensitif sebum-control bebas alkohol pengering untuk melindungi kulit berminyak sensitif.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_SEDANG: {
    dasarKlinis: "Tabir surya mineral fisik non-iritan bebas wewangian dengan penenang aktif kulit berminyak sensitif jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  BERMINYAK_TRUE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik murni bebas minyak dan wewangian dengan penenang kuat kulit berminyak sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_BIASA: {
    dasarKlinis: "Tabir surya hibrida ringan proteksi UV seimbang tanpa oklusi zona-T untuk kulit kombinasi biasa.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_SEDANG: {
    dasarKlinis: "Tabir surya fluid non-komedogenik bebas minyak oklusif berat untuk kulit kombinasi jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_FALSE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik fluid ringan bebas lipid oklusif untuk memitigasi jerawat parah kulit kombinasi.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_BIASA: {
    dasarKlinis: "Tabir surya sensitif krim-gel ringan bebas alkohol pengering untuk melindungi kulit kombinasi sensitif.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_SEDANG: {
    dasarKlinis: "Tabir surya mineral fisik non-iritan dengan penenang aktif bebas pewangi untuk kulit kombinasi sensitif jerawat sedang.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  KOMBINASI_TRUE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik murni bebas minyak dengan penenang kuat kulit kombinasi sensitif jerawat parah.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_BIASA: {
    dasarKlinis: "Tabir surya hibrida krim sedang hidrasi seimbang untuk kulit normal biasa.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 5,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 3 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" }
  },
  NORMAL_FALSE_SEDANG: {
    dasarKlinis: "Tabir surya fluid non-komedogenik bebas minyak oklusif berat untuk kulit normal jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_FALSE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik fluid ringan bebas lipid oklusif untuk memitigasi jerawat parah kulit normal.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 3,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistMedium: { status: "DILARANG", minCount: 0, maxCount: 0 },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_BIASA: {
    dasarKlinis: "Tabir surya sensitif hibrida krim sedang bebas alkohol pengering untuk melindungi kulit normal sensitif.",
    maxSingleComedo: 3,
    maxMultiComedoLoad: 5,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 4 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" }
  },
  NORMAL_TRUE_SEDANG: {
    dasarKlinis: "Tabir surya mineral fisik bebas wewangian dengan penenang aktif untuk kulit normal sensitif jerawat sedang.",
    maxSingleComedo: 2,
    maxMultiComedoLoad: 4,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  },
  NORMAL_TRUE_PARAH: {
    dasarKlinis: "Tabir surya mineral fisik lembut bebas iritan untuk melindungi barrier kulit normal sensitif dari paparan UV.",
    maxSingleComedo: 1,
    maxMultiComedoLoad: 2,
    harsh: { status: "DILARANG", maxLoad: 0 },
    buffer: { status: "WAJIB", minLoad: 5 },
    surfactant: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    uvFilter: { status: "WAJIB", minCount: 2, maxCount: "UNLIMITED" },
    moistLight: { status: "DIIZINKAN", minCount: 0, maxCount: "UNLIMITED" },
    moistMedium: { status: "WAJIB", minCount: 1, maxCount: "UNLIMITED" },
    moistHeavy: { status: "DILARANG", minCount: 0, maxCount: 0 }
  }
};
